### ISSUE TITLE
Create documentation for the repository

### ISSUE THREAD

**Issue by Haleshot** [marimo-team/mkdocs-marimo#20]
Create a documentation (github.io website) for the repo with the https://github.com/marimo-team/mkdocs-marimo repo.
Would be nice to have a website where users can see examples embedded in a website manner.

**Comment by Haleshot** [comment]
Ok, meant to create the issue in my [repository](https://github.com/Haleshot/marimo-tutorials); sorry for the ping 🙈

**Comment by mscolnick** [comment]
All good 😂

@Haleshot it would be great if you can try this for your repo and provide some feedback (on setup or features/bugs)

**Comment by Haleshot** [comment]
Already created an issue in the repo for it - https://github.com/Haleshot/marimo-tutorials/issues/40; the next few weeks -> my college reopens -> final year project submissions -> final sem exams. Will try my best to implement this and get something working/up and running.
